# Assignment 5

1. Choose a regression dataset (bikeshare is allowed), perform a test/train split, and build a regression model (just like in assingnment 3), and calculate the 
    + Training Error (MSE, MAE)
    + Testing Error (MSE, MAE)
2. Choose a classification dataset (not the adult.data set, The UCI repository has many datasets as well as Kaggle), perform test/train split and create a classification model (your choice but DecisionTree is fine). Calculate 
    + Accuracy
    + Confusion Matrix
    + Classifcation Report
    
3. (Bonus) See if you can improve the classification model's performance with any tricks you can think of (modify features, remove features, polynomial features)

In [18]:
# Part 1: Regression

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = 20, 10
import pandas as pd
import numpy as np
bikes = pd.read_csv('C:/Users/caprile/Desktop/mlnn/data/bikeshare.csv.gz')
bikes['start'] = pd.to_datetime(bikes['Start date'], infer_datetime_format=True)
bikes['end'] = pd.to_datetime(bikes['End date'], infer_datetime_format=True)
bikes["dur"] = (bikes['Duration (ms)']/1000).astype(int)

bikes['hour_of_day'] = (bikes.start.dt.hour + (bikes.start.dt.minute//6)/10)
bikes.head()

In [3]:
reg_bikes = bikes[bikes['Member Type']=='Registered']
hours = reg_bikes.groupby([reg_bikes.hour_of_day, reg_bikes.start.dt.dayofweek]).agg('count')
hours['hour'] = hours.index
day_hour_count = hours.dur.unstack()
day_hour_count.head()

start           0     1     2     3     4     5      6
hour_of_day                                           
0.0          21.0  34.0  43.0  47.0  51.0  89.0  106.0
0.1          39.0  22.0  27.0  37.0  56.0  87.0  100.0
0.2          31.0  24.0  26.0  42.0  50.0  98.0   77.0
0.3          26.0  27.0  25.0  29.0  52.0  99.0   87.0
0.4          19.0  24.0  29.0  29.0  50.0  98.0   69.0

In [12]:
day_hour_count = day_hour_count.dropna()
monday = day_hour_count[0]
x = day_hour_count.index
x = np.asarray(x)
x = x.reshape(-1, 1)
y = monday

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.5)

In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)
model.coef_, model.intercept_

(array([12.15312983]), 137.5856529415003)

In [16]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, np.dot(x_test, model.coef_) + model.intercept_)

68937.73239806974

In [17]:
mean_squared_error(y_train, np.dot(x_train, model.coef_) + model.intercept_)

62017.1055061585

In [ ]:
# Part 2: Classification

In [21]:
breast_cancer = pd.read_csv('C:/Users/caprile/Downloads/dataR2.csv')
breast_cancer.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [24]:
x_train, x_test, y_train, y_test = train_test_split(breast_cancer.drop(['Classification'], axis=1),breast_cancer.Classification, test_size=.50)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy')

In [25]:
model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [28]:
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix, auc, roc_curve
                            )

In [29]:
test_predictions = model.predict(x_test)
accuracy_score(y_test, test_predictions)

0.7241379310344828

In [30]:
confusion_matrix(y_test, test_predictions)

array([[20,  2],
       [14, 22]], dtype=int64)

In [31]:
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           1       0.59      0.91      0.71        22
           2       0.92      0.61      0.73        36

    accuracy                           0.72        58
   macro avg       0.75      0.76      0.72        58
weighted avg       0.79      0.72      0.73        58



In [32]:
train_predictions = model.predict(x_train)
accuracy_score(y_train, train_predictions)

1.0

In [33]:
confusion_matrix(y_train, train_predictions)

array([[30,  0],
       [ 0, 28]], dtype=int64)

In [34]:
print(classification_report(y_train, train_predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        30
           2       1.00      1.00      1.00        28

    accuracy                           1.00        58
   macro avg       1.00      1.00      1.00        58
weighted avg       1.00      1.00      1.00        58

